/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingsIndexRouteImport } from './routes/trainings.index'
import { Route as ContestIndexRouteImport } from './routes/contest.index'
import { Route as TrainingsIdRouteImport } from './routes/trainings.$id'
import { Route as SurveyTokenRouteImport } from './routes/survey.$token'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentLoginRouteImport } from './routes/student.login'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ContestSubmitRouteImport } from './routes/contest.submit'
import { Route as ContestRegisterRouteImport } from './routes/contest.register'
import { Route as AdvisorRegisterRouteImport } from './routes/advisor.register'
import { Route as AdvisorQueueRouteImport } from './routes/advisor.queue'
import { Route as AdvisorDashboardRouteImport } from './routes/advisor.dashboard'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicTrainingsNotifyRegistrationRouteImport } from './routes/api/public/trainings/notify-registration'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingsIndexRoute = TrainingsIndexRouteImport.update({
  id: '/trainings/',
  path: '/trainings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestIndexRoute = ContestIndexRouteImport.update({
  id: '/contest/',
  path: '/contest/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingsIdRoute = TrainingsIdRouteImport.update({
  id: '/trainings/$id',
  path: '/trainings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyTokenRoute = SurveyTokenRouteImport.update({
  id: '/survey/$token',
  path: '/survey/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student/login',
  path: '/student/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestSubmitRoute = ContestSubmitRouteImport.update({
  id: '/contest/submit',
  path: '/contest/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestRegisterRoute = ContestRegisterRouteImport.update({
  id: '/contest/register',
  path: '/contest/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRegisterRoute = AdvisorRegisterRouteImport.update({
  id: '/advisor/register',
  path: '/advisor/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorQueueRoute = AdvisorQueueRouteImport.update({
  id: '/advisor/queue',
  path: '/advisor/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorDashboardRoute = AdvisorDashboardRouteImport.update({
  id: '/advisor/dashboard',
  path: '/advisor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrainingsNotifyRegistrationRoute =
  ApiPublicTrainingsNotifyRegistrationRouteImport.update({
    id: '/api/public/trainings/notify-registration',
    path: '/api/public/trainings/notify-registration',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/set-password': typeof SetPasswordRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/advisor/dashboard': typeof AdvisorDashboardRoute
  '/advisor/queue': typeof AdvisorQueueRoute
  '/advisor/register': typeof AdvisorRegisterRoute
  '/contest/register': typeof ContestRegisterRoute
  '/contest/submit': typeof ContestSubmitRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/s/$token': typeof STokenRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/login': typeof StudentLoginRoute
  '/student/profile': typeof StudentProfileRoute
  '/survey/$token': typeof SurveyTokenRoute
  '/trainings/$id': typeof TrainingsIdRoute
  '/contest/': typeof ContestIndexRoute
  '/trainings/': typeof TrainingsIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/trainings/notify-registration': typeof ApiPublicTrainingsNotifyRegistrationRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/set-password': typeof SetPasswordRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/advisor/dashboard': typeof AdvisorDashboardRoute
  '/advisor/queue': typeof AdvisorQueueRoute
  '/advisor/register': typeof AdvisorRegisterRoute
  '/contest/register': typeof ContestRegisterRoute
  '/contest/submit': typeof ContestSubmitRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/s/$token': typeof STokenRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/login': typeof StudentLoginRoute
  '/student/profile': typeof StudentProfileRoute
  '/survey/$token': typeof SurveyTokenRoute
  '/trainings/$id': typeof TrainingsIdRoute
  '/contest': typeof ContestIndexRoute
  '/trainings': typeof TrainingsIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/trainings/notify-registration': typeof ApiPublicTrainingsNotifyRegistrationRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/set-password': typeof SetPasswordRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/advisor/dashboard': typeof AdvisorDashboardRoute
  '/advisor/queue': typeof AdvisorQueueRoute
  '/advisor/register': typeof AdvisorRegisterRoute
  '/contest/register': typeof ContestRegisterRoute
  '/contest/submit': typeof ContestSubmitRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/s/$token': typeof STokenRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/login': typeof StudentLoginRoute
  '/student/profile': typeof StudentProfileRoute
  '/survey/$token': typeof SurveyTokenRoute
  '/trainings/$id': typeof TrainingsIdRoute
  '/contest/': typeof ContestIndexRoute
  '/trainings/': typeof TrainingsIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/trainings/notify-registration': typeof ApiPublicTrainingsNotifyRegistrationRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/partners'
    | '/set-password'
    | '/signup'
    | '/unsubscribe'
    | '/advisor/dashboard'
    | '/advisor/queue'
    | '/advisor/register'
    | '/contest/register'
    | '/contest/submit'
    | '/email/unsubscribe'
    | '/s/$token'
    | '/student/dashboard'
    | '/student/login'
    | '/student/profile'
    | '/survey/$token'
    | '/trainings/$id'
    | '/contest/'
    | '/trainings/'
    | '/lovable/email/suppression'
    | '/api/public/trainings/notify-registration'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/partners'
    | '/set-password'
    | '/signup'
    | '/unsubscribe'
    | '/advisor/dashboard'
    | '/advisor/queue'
    | '/advisor/register'
    | '/contest/register'
    | '/contest/submit'
    | '/email/unsubscribe'
    | '/s/$token'
    | '/student/dashboard'
    | '/student/login'
    | '/student/profile'
    | '/survey/$token'
    | '/trainings/$id'
    | '/contest'
    | '/trainings'
    | '/lovable/email/suppression'
    | '/api/public/trainings/notify-registration'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/partners'
    | '/set-password'
    | '/signup'
    | '/unsubscribe'
    | '/advisor/dashboard'
    | '/advisor/queue'
    | '/advisor/register'
    | '/contest/register'
    | '/contest/submit'
    | '/email/unsubscribe'
    | '/s/$token'
    | '/student/dashboard'
    | '/student/login'
    | '/student/profile'
    | '/survey/$token'
    | '/trainings/$id'
    | '/contest/'
    | '/trainings/'
    | '/lovable/email/suppression'
    | '/api/public/trainings/notify-registration'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PartnersRoute: typeof PartnersRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SignupRoute: typeof SignupRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdvisorDashboardRoute: typeof AdvisorDashboardRoute
  AdvisorQueueRoute: typeof AdvisorQueueRoute
  AdvisorRegisterRoute: typeof AdvisorRegisterRoute
  ContestRegisterRoute: typeof ContestRegisterRoute
  ContestSubmitRoute: typeof ContestSubmitRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  STokenRoute: typeof STokenRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentLoginRoute: typeof StudentLoginRoute
  StudentProfileRoute: typeof StudentProfileRoute
  SurveyTokenRoute: typeof SurveyTokenRoute
  TrainingsIdRoute: typeof TrainingsIdRoute
  ContestIndexRoute: typeof ContestIndexRoute
  TrainingsIndexRoute: typeof TrainingsIndexRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicTrainingsNotifyRegistrationRoute: typeof ApiPublicTrainingsNotifyRegistrationRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainings/': {
      id: '/trainings/'
      path: '/trainings'
      fullPath: '/trainings/'
      preLoaderRoute: typeof TrainingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contest/': {
      id: '/contest/'
      path: '/contest'
      fullPath: '/contest/'
      preLoaderRoute: typeof ContestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainings/$id': {
      id: '/trainings/$id'
      path: '/trainings/$id'
      fullPath: '/trainings/$id'
      preLoaderRoute: typeof TrainingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey/$token': {
      id: '/survey/$token'
      path: '/survey/$token'
      fullPath: '/survey/$token'
      preLoaderRoute: typeof SurveyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/login': {
      id: '/student/login'
      path: '/student/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contest/submit': {
      id: '/contest/submit'
      path: '/contest/submit'
      fullPath: '/contest/submit'
      preLoaderRoute: typeof ContestSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contest/register': {
      id: '/contest/register'
      path: '/contest/register'
      fullPath: '/contest/register'
      preLoaderRoute: typeof ContestRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/register': {
      id: '/advisor/register'
      path: '/advisor/register'
      fullPath: '/advisor/register'
      preLoaderRoute: typeof AdvisorRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/queue': {
      id: '/advisor/queue'
      path: '/advisor/queue'
      fullPath: '/advisor/queue'
      preLoaderRoute: typeof AdvisorQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/dashboard': {
      id: '/advisor/dashboard'
      path: '/advisor/dashboard'
      fullPath: '/advisor/dashboard'
      preLoaderRoute: typeof AdvisorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trainings/notify-registration': {
      id: '/api/public/trainings/notify-registration'
      path: '/api/public/trainings/notify-registration'
      fullPath: '/api/public/trainings/notify-registration'
      preLoaderRoute: typeof ApiPublicTrainingsNotifyRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PartnersRoute: PartnersRoute,
  SetPasswordRoute: SetPasswordRoute,
  SignupRoute: SignupRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdvisorDashboardRoute: AdvisorDashboardRoute,
  AdvisorQueueRoute: AdvisorQueueRoute,
  AdvisorRegisterRoute: AdvisorRegisterRoute,
  ContestRegisterRoute: ContestRegisterRoute,
  ContestSubmitRoute: ContestSubmitRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  STokenRoute: STokenRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentLoginRoute: StudentLoginRoute,
  StudentProfileRoute: StudentProfileRoute,
  SurveyTokenRoute: SurveyTokenRoute,
  TrainingsIdRoute: TrainingsIdRoute,
  ContestIndexRoute: ContestIndexRoute,
  TrainingsIndexRoute: TrainingsIndexRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicTrainingsNotifyRegistrationRoute:
    ApiPublicTrainingsNotifyRegistrationRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
